// Code generated by protoc-gen-go. DO NOT EDIT.
// source: leagueservice/league.proto

package leagueservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SummonerProfile struct {
	ProfileIconId        int32    `protobuf:"varint,1,opt,name=profileIconId,proto3" json:"profileIconId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Puuid                string   `protobuf:"bytes,3,opt,name=puuid,proto3" json:"puuid,omitempty"`
	SummonerLevel        int64    `protobuf:"varint,4,opt,name=summonerLevel,proto3" json:"summonerLevel,omitempty"`
	RevisionDate         int64    `protobuf:"varint,5,opt,name=revisionDate,proto3" json:"revisionDate,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            string   `protobuf:"bytes,7,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummonerProfile) Reset()         { *m = SummonerProfile{} }
func (m *SummonerProfile) String() string { return proto.CompactTextString(m) }
func (*SummonerProfile) ProtoMessage()    {}
func (*SummonerProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7af40a0700cd5cf, []int{0}
}

func (m *SummonerProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummonerProfile.Unmarshal(m, b)
}
func (m *SummonerProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummonerProfile.Marshal(b, m, deterministic)
}
func (m *SummonerProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummonerProfile.Merge(m, src)
}
func (m *SummonerProfile) XXX_Size() int {
	return xxx_messageInfo_SummonerProfile.Size(m)
}
func (m *SummonerProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_SummonerProfile.DiscardUnknown(m)
}

var xxx_messageInfo_SummonerProfile proto.InternalMessageInfo

func (m *SummonerProfile) GetProfileIconId() int32 {
	if m != nil {
		return m.ProfileIconId
	}
	return 0
}

func (m *SummonerProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SummonerProfile) GetPuuid() string {
	if m != nil {
		return m.Puuid
	}
	return ""
}

func (m *SummonerProfile) GetSummonerLevel() int64 {
	if m != nil {
		return m.SummonerLevel
	}
	return 0
}

func (m *SummonerProfile) GetRevisionDate() int64 {
	if m != nil {
		return m.RevisionDate
	}
	return 0
}

func (m *SummonerProfile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SummonerProfile) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type Match struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7af40a0700cd5cf, []int{1}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

type MatchDetail struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchDetail) Reset()         { *m = MatchDetail{} }
func (m *MatchDetail) String() string { return proto.CompactTextString(m) }
func (*MatchDetail) ProtoMessage()    {}
func (*MatchDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7af40a0700cd5cf, []int{2}
}

func (m *MatchDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchDetail.Unmarshal(m, b)
}
func (m *MatchDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchDetail.Marshal(b, m, deterministic)
}
func (m *MatchDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchDetail.Merge(m, src)
}
func (m *MatchDetail) XXX_Size() int {
	return xxx_messageInfo_MatchDetail.Size(m)
}
func (m *MatchDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchDetail.DiscardUnknown(m)
}

var xxx_messageInfo_MatchDetail proto.InternalMessageInfo

type GetSummonerStatsRequest struct {
	SummonerName         string   `protobuf:"bytes,1,opt,name=summoner_name,json=summonerName,proto3" json:"summoner_name,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSummonerStatsRequest) Reset()         { *m = GetSummonerStatsRequest{} }
func (m *GetSummonerStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSummonerStatsRequest) ProtoMessage()    {}
func (*GetSummonerStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7af40a0700cd5cf, []int{3}
}

func (m *GetSummonerStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSummonerStatsRequest.Unmarshal(m, b)
}
func (m *GetSummonerStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSummonerStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetSummonerStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSummonerStatsRequest.Merge(m, src)
}
func (m *GetSummonerStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSummonerStatsRequest.Size(m)
}
func (m *GetSummonerStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSummonerStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSummonerStatsRequest proto.InternalMessageInfo

func (m *GetSummonerStatsRequest) GetSummonerName() string {
	if m != nil {
		return m.SummonerName
	}
	return ""
}

func (m *GetSummonerStatsRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type GetSummonerStatsResponse struct {
	SummonerProfile      *SummonerProfile `protobuf:"bytes,1,opt,name=summonerProfile,proto3" json:"summonerProfile,omitempty"`
	MatchHistory         []*Match         `protobuf:"bytes,2,rep,name=match_history,json=matchHistory,proto3" json:"match_history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetSummonerStatsResponse) Reset()         { *m = GetSummonerStatsResponse{} }
func (m *GetSummonerStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSummonerStatsResponse) ProtoMessage()    {}
func (*GetSummonerStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7af40a0700cd5cf, []int{4}
}

func (m *GetSummonerStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSummonerStatsResponse.Unmarshal(m, b)
}
func (m *GetSummonerStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSummonerStatsResponse.Marshal(b, m, deterministic)
}
func (m *GetSummonerStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSummonerStatsResponse.Merge(m, src)
}
func (m *GetSummonerStatsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSummonerStatsResponse.Size(m)
}
func (m *GetSummonerStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSummonerStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSummonerStatsResponse proto.InternalMessageInfo

func (m *GetSummonerStatsResponse) GetSummonerProfile() *SummonerProfile {
	if m != nil {
		return m.SummonerProfile
	}
	return nil
}

func (m *GetSummonerStatsResponse) GetMatchHistory() []*Match {
	if m != nil {
		return m.MatchHistory
	}
	return nil
}

func init() {
	proto.RegisterType((*SummonerProfile)(nil), "leagueservice.SummonerProfile")
	proto.RegisterType((*Match)(nil), "leagueservice.Match")
	proto.RegisterType((*MatchDetail)(nil), "leagueservice.MatchDetail")
	proto.RegisterType((*GetSummonerStatsRequest)(nil), "leagueservice.GetSummonerStatsRequest")
	proto.RegisterType((*GetSummonerStatsResponse)(nil), "leagueservice.GetSummonerStatsResponse")
}

func init() { proto.RegisterFile("leagueservice/league.proto", fileDescriptor_c7af40a0700cd5cf) }

var fileDescriptor_c7af40a0700cd5cf = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x99, 0x74, 0xdb, 0xa5, 0xaf, 0xad, 0x85, 0x61, 0xd5, 0xa1, 0xd4, 0xa5, 0xc4, 0x45,
	0x73, 0x6a, 0xb4, 0x9e, 0x3c, 0xba, 0x14, 0xdc, 0xc2, 0x2a, 0x92, 0x45, 0x0f, 0x5e, 0x96, 0x31,
	0x79, 0x76, 0x07, 0x92, 0x99, 0x38, 0x33, 0x09, 0x2c, 0xe2, 0xc5, 0x0f, 0xe0, 0x41, 0x3f, 0x80,
	0x1f, 0xca, 0x93, 0x77, 0x3f, 0x88, 0x64, 0xd2, 0xb2, 0x4c, 0x44, 0xbc, 0x78, 0x7b, 0xef, 0x9f,
	0x7f, 0xfe, 0x79, 0xbf, 0x37, 0x19, 0x98, 0xe5, 0xc8, 0xb7, 0x15, 0x1a, 0xd4, 0xb5, 0x48, 0x31,
	0x6e, 0xbb, 0x65, 0xa9, 0x95, 0x55, 0x74, 0xe2, 0x3d, 0x9b, 0xcd, 0xb7, 0x4a, 0x6d, 0x73, 0x8c,
	0x79, 0x29, 0x62, 0x2e, 0xa5, 0xb2, 0xdc, 0x0a, 0x25, 0x4d, 0x6b, 0x0e, 0x7f, 0x12, 0x98, 0x5e,
	0x54, 0x45, 0xa1, 0x24, 0xea, 0x57, 0x5a, 0xbd, 0x17, 0x39, 0xd2, 0x13, 0x98, 0x94, 0x6d, 0xb9,
	0x49, 0x95, 0xdc, 0x64, 0x8c, 0x2c, 0x48, 0xd4, 0x4f, 0x7c, 0x91, 0x52, 0x38, 0x90, 0xbc, 0x40,
	0x16, 0x2c, 0x48, 0x34, 0x4c, 0x5c, 0x4d, 0x8f, 0xa0, 0x5f, 0x56, 0x95, 0xc8, 0x58, 0xcf, 0x89,
	0x6d, 0xd3, 0xe4, 0x99, 0xdd, 0x27, 0xce, 0xb1, 0xc6, 0x9c, 0x1d, 0x2c, 0x48, 0xd4, 0x4b, 0x7c,
	0x91, 0x86, 0x30, 0xd6, 0x58, 0x0b, 0x23, 0x94, 0x5c, 0x73, 0x8b, 0xac, 0xef, 0x4c, 0x9e, 0x46,
	0x6f, 0x41, 0x20, 0x32, 0x36, 0x70, 0xe1, 0x81, 0xc8, 0xe8, 0x1c, 0x86, 0x3c, 0x4d, 0x55, 0x25,
	0xed, 0x26, 0x63, 0x87, 0x4e, 0xbe, 0x11, 0xc2, 0x43, 0xe8, 0xbf, 0xe0, 0x36, 0xbd, 0x0a, 0x27,
	0x30, 0x72, 0xc5, 0x1a, 0x2d, 0x17, 0x79, 0xf8, 0x06, 0xee, 0x3e, 0x47, 0xbb, 0xa7, 0xbe, 0xb0,
	0xdc, 0x9a, 0x04, 0x3f, 0x54, 0x68, 0x2c, 0xbd, 0x7f, 0x33, 0xea, 0xa5, 0xa3, 0x23, 0x2e, 0x74,
	0xbc, 0x17, 0x5f, 0x36, 0x94, 0x77, 0x60, 0xa0, 0x71, 0x2b, 0x94, 0xdc, 0xb1, 0xef, 0xba, 0xf0,
	0x3b, 0x01, 0xf6, 0x67, 0xb0, 0x29, 0x95, 0x34, 0x48, 0xcf, 0x60, 0x6a, 0xfc, 0x3d, 0xbb, 0xec,
	0xd1, 0xea, 0x78, 0xe9, 0x9d, 0xd7, 0xb2, 0x73, 0x1a, 0x49, 0xf7, 0x35, 0xfa, 0x14, 0x26, 0x45,
	0x43, 0x73, 0x79, 0x25, 0x8c, 0x55, 0xfa, 0x9a, 0x05, 0x8b, 0x5e, 0x34, 0x5a, 0x1d, 0x75, 0x72,
	0x1c, 0x71, 0x32, 0x76, 0xd6, 0xb3, 0xd6, 0xb9, 0xfa, 0x1a, 0xc0, 0xf0, 0xdc, 0xb9, 0x9e, 0x95,
	0x82, 0x7e, 0x21, 0x70, 0xbb, 0x3b, 0xef, 0x6b, 0xc9, 0xf5, 0x35, 0x7d, 0xd0, 0xc9, 0xfa, 0xcb,
	0xba, 0x66, 0x0f, 0xff, 0xe9, 0x6b, 0xe9, 0xc3, 0x93, 0xcf, 0x3f, 0x7e, 0x7d, 0x0b, 0x8e, 0xe9,
	0x3c, 0xae, 0x1f, 0xc7, 0x7b, 0xa0, 0xf8, 0xa3, 0xb7, 0xeb, 0x4f, 0xd4, 0xc2, 0xbd, 0x6e, 0xc2,
	0xa9, 0x58, 0x0b, 0x8d, 0x69, 0xf3, 0xcb, 0xf2, 0xfc, 0xbf, 0xcf, 0x15, 0x91, 0x47, 0xe4, 0x74,
	0xfa, 0xd6, 0xbf, 0x31, 0xef, 0x06, 0xee, 0x6a, 0x3c, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xbf,
	0xcd, 0x6b, 0xd4, 0x65, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LeagueApiClient is the client API for LeagueApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LeagueApiClient interface {
	GetSummonerStatsUnary(ctx context.Context, in *GetSummonerStatsRequest, opts ...grpc.CallOption) (*GetSummonerStatsResponse, error)
	GetSummonerStatsBiDirectional(ctx context.Context, opts ...grpc.CallOption) (LeagueApi_GetSummonerStatsBiDirectionalClient, error)
}

type leagueApiClient struct {
	cc *grpc.ClientConn
}

func NewLeagueApiClient(cc *grpc.ClientConn) LeagueApiClient {
	return &leagueApiClient{cc}
}

func (c *leagueApiClient) GetSummonerStatsUnary(ctx context.Context, in *GetSummonerStatsRequest, opts ...grpc.CallOption) (*GetSummonerStatsResponse, error) {
	out := new(GetSummonerStatsResponse)
	err := c.cc.Invoke(ctx, "/leagueservice.LeagueApi/GetSummonerStatsUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leagueApiClient) GetSummonerStatsBiDirectional(ctx context.Context, opts ...grpc.CallOption) (LeagueApi_GetSummonerStatsBiDirectionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LeagueApi_serviceDesc.Streams[0], "/leagueservice.LeagueApi/GetSummonerStatsBiDirectional", opts...)
	if err != nil {
		return nil, err
	}
	x := &leagueApiGetSummonerStatsBiDirectionalClient{stream}
	return x, nil
}

type LeagueApi_GetSummonerStatsBiDirectionalClient interface {
	Send(*GetSummonerStatsRequest) error
	Recv() (*GetSummonerStatsResponse, error)
	grpc.ClientStream
}

type leagueApiGetSummonerStatsBiDirectionalClient struct {
	grpc.ClientStream
}

func (x *leagueApiGetSummonerStatsBiDirectionalClient) Send(m *GetSummonerStatsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *leagueApiGetSummonerStatsBiDirectionalClient) Recv() (*GetSummonerStatsResponse, error) {
	m := new(GetSummonerStatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LeagueApiServer is the server API for LeagueApi service.
type LeagueApiServer interface {
	GetSummonerStatsUnary(context.Context, *GetSummonerStatsRequest) (*GetSummonerStatsResponse, error)
	GetSummonerStatsBiDirectional(LeagueApi_GetSummonerStatsBiDirectionalServer) error
}

func RegisterLeagueApiServer(s *grpc.Server, srv LeagueApiServer) {
	s.RegisterService(&_LeagueApi_serviceDesc, srv)
}

func _LeagueApi_GetSummonerStatsUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummonerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeagueApiServer).GetSummonerStatsUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leagueservice.LeagueApi/GetSummonerStatsUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeagueApiServer).GetSummonerStatsUnary(ctx, req.(*GetSummonerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeagueApi_GetSummonerStatsBiDirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LeagueApiServer).GetSummonerStatsBiDirectional(&leagueApiGetSummonerStatsBiDirectionalServer{stream})
}

type LeagueApi_GetSummonerStatsBiDirectionalServer interface {
	Send(*GetSummonerStatsResponse) error
	Recv() (*GetSummonerStatsRequest, error)
	grpc.ServerStream
}

type leagueApiGetSummonerStatsBiDirectionalServer struct {
	grpc.ServerStream
}

func (x *leagueApiGetSummonerStatsBiDirectionalServer) Send(m *GetSummonerStatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *leagueApiGetSummonerStatsBiDirectionalServer) Recv() (*GetSummonerStatsRequest, error) {
	m := new(GetSummonerStatsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _LeagueApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "leagueservice.LeagueApi",
	HandlerType: (*LeagueApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSummonerStatsUnary",
			Handler:    _LeagueApi_GetSummonerStatsUnary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSummonerStatsBiDirectional",
			Handler:       _LeagueApi_GetSummonerStatsBiDirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "leagueservice/league.proto",
}
